### ISSUE TITLE
Handle empty top-level chapters

### ISSUE THREAD

**Issue by msuchane** [msuchane/cizrna#1]
The top-level chapters that Acorns generates are intended to be included from `main.adoc` or some other manual content. However, if a chapter captures no release notes, and is empty as a result, Acorns generates nothing in its place. That causes the external include to fail.

Figure out the best solution to empty chapters. Options:

- Generate an empty file that satisfies the external include but doesn't appear in the rendered document. Is non-modular.
- Just fail and let the RN maintainer handle it by commenting out the broken includes. They might forget to re-enable the includes later.
- Fail while generating the file and let the RN maintainer comment out the template. They might forget to re-enable the template later.

Another option:

Acorns can automatically comment out include statements in `main.adoc` if they target files that this run hasn't generated. The next time the file is generated, Acorns could uncomment the include.

Advantages:

- A clean, modular solution.
- Doesn't risk the breakage caused by manual maintenance.

Disadvantages:

- The RN maintainer might still delete the commented-out include and cause surprises.
- The `main.adoc` file is technically manual content, so this solution somewhat violates the barrier between generated and manual.

**Comment by msuchane** [comment]
Lenka, Gabi, and Lucie all prefer option 1 (empty files).

Alternatively, Lucie is partial to option 4 (commented-out includes) with an all-caps warning.

**Comment by jamsmithredhat** [comment]
James is ok with option 1 (empty files) or option 4 (commented-out includes).
Would like to see a solution soon. 
Getting an error message, manually commenting out the include statement, and rebuilding is disruptive.
Even worse it the risk of commenting out an include statement and neglecting to uncomment it when you get some bugs that belong in the included file.
Thanks

**Comment by msuchane** [comment]
I'm happy with the "empty files" solution.

I was hesitant to implement it because empty assemblies technically violate FCC modularity rules, and our future tooling could have had a problem with it. At this point, it's no longer an issue, and I believe that the convenience of reliably working include statements greatly outweighs the theoretical modularity issues.

I'm going to implement this behavior shortly.

**Comment by msuchane** [comment]
@jamsmithredhat, I've resolved this issue, choosing option 1.

With version 1.0.0, acorns now generates empty AsciiDoc files for all top-level assemblies that are empty. As such, you can include all assemblies in your master file, and the include directives won't break.
