### ISSUE TITLE
Generate a footnote for private BZ/Jira IDs with no link

### ISSUE THREAD

**Issue by soulcharmer** [msuchane/cizrna#24]
Sharing the condition with #22 , if a ticket is private, we should generate a footnote for the ticket ID explaining why there's no link, to prevent recurring bug reports from readers.

In Jira, the Security Level field shall govern if and how private a ticket is.

**Comment by msuchane** [comment]
With version 0.27.0, non-clickable IDs now feature the following footnote:

> This ticket is not publicly accessible. Therefore, the release note does not include a link to the ticket.

You can override the footnote text in your document using the `{PrivateFootnote}` attribute.
