### ISSUE TITLE
Incorrect error in bug status

### ISSUE THREAD

**Issue by lspackova** [msuchane/cizrna#25]
Bug status table reports "RN not needed." even for notes that have a valid doc type (like Bug Fix) but previously were marked as No doc update (see BZ#2121709, BZ#2143878).

**Comment by msuchane** [comment]
@lspackova, as far as I can tell, both of those bugs are set as RDT-, which Cizrna reports as "RN not needed." Is that behavior confusing or unexpected? What message would you prefer instead?

**Comment by lspackova** [comment]
@msuchane Thanks a lot for noticing! So the issue is in Bugzilla. It sets the RDT- flag when you set No doc update but if you change it to some other doc type, it leaves the RDT-.
